version: '3'

services:
  web:
    image: ebiven/vue-cli
    environment:
    - HOST=0.0.0.0
    volumes:
      - ./app:/code
    working_dir: /code
    command: npm install
    command: npm run serve
    ports:
      - "8080:8080"
    restart: always